import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const myFont = localFont({
  src: [
    {
      path: "../public/fonts/MADEOkineSansPERSONALUSE-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/MADEOkineSansPERSONALUSE-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/MADEOkineSansPERSONALUSE-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/MADEOkineSansPERSONALUSE-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${myFont.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
